################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Each subdirectory must supply rules for building sources it contributes
controlSUITE/F2837xS/F2837xS_common/source/F2837xS_Adc.obj: ../controlSUITE/F2837xS/F2837xS_common/source/F2837xS_Adc.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-c2000_6.4.6/bin/cl2000" -v28 -ml -mt --cla_support=cla1 --float_support=fpu32 --tmu_support=tmu0 --vcu_support=vcu2 --fp_mode=relaxed --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/usblib/host" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/third_party/fatfs/src" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/utils" --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-c2000_6.4.6/include" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/usblib" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/third_party/fatfs/src" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/driverlib" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/usblib/device" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/inc" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/include" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_headers/include" --advice:performance=all -g --define=DISK0_USB_MSC --define=CPU1 --define=_FLASH --define=ccs_c2k --define=DISK1_USB_MSC --diag_warning=225 --display_error_number --diag_wrap=off --preproc_with_compile --preproc_dependency="controlSUITE/F2837xS/F2837xS_common/source/F2837xS_Adc.pp" --obj_directory="controlSUITE/F2837xS/F2837xS_common/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

controlSUITE/F2837xS/F2837xS_common/source/F2837xS_CodeStartBranch.obj: ../controlSUITE/F2837xS/F2837xS_common/source/F2837xS_CodeStartBranch.asm $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-c2000_6.4.6/bin/cl2000" -v28 -ml -mt --cla_support=cla1 --float_support=fpu32 --tmu_support=tmu0 --vcu_support=vcu2 --fp_mode=relaxed --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/usblib/host" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/third_party/fatfs/src" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/utils" --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-c2000_6.4.6/include" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/usblib" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/third_party/fatfs/src" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/driverlib" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/usblib/device" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/inc" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/include" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_headers/include" --advice:performance=all -g --define=DISK0_USB_MSC --define=CPU1 --define=_FLASH --define=ccs_c2k --define=DISK1_USB_MSC --diag_warning=225 --display_error_number --diag_wrap=off --preproc_with_compile --preproc_dependency="controlSUITE/F2837xS/F2837xS_common/source/F2837xS_CodeStartBranch.pp" --obj_directory="controlSUITE/F2837xS/F2837xS_common/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

controlSUITE/F2837xS/F2837xS_common/source/F2837xS_CpuTimers.obj: ../controlSUITE/F2837xS/F2837xS_common/source/F2837xS_CpuTimers.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-c2000_6.4.6/bin/cl2000" -v28 -ml -mt --cla_support=cla1 --float_support=fpu32 --tmu_support=tmu0 --vcu_support=vcu2 --fp_mode=relaxed --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/usblib/host" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/third_party/fatfs/src" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/utils" --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-c2000_6.4.6/include" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/usblib" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/third_party/fatfs/src" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/driverlib" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/usblib/device" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/inc" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/include" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_headers/include" --advice:performance=all -g --define=DISK0_USB_MSC --define=CPU1 --define=_FLASH --define=ccs_c2k --define=DISK1_USB_MSC --diag_warning=225 --display_error_number --diag_wrap=off --preproc_with_compile --preproc_dependency="controlSUITE/F2837xS/F2837xS_common/source/F2837xS_CpuTimers.pp" --obj_directory="controlSUITE/F2837xS/F2837xS_common/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

controlSUITE/F2837xS/F2837xS_common/source/F2837xS_DBGIER.obj: ../controlSUITE/F2837xS/F2837xS_common/source/F2837xS_DBGIER.asm $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-c2000_6.4.6/bin/cl2000" -v28 -ml -mt --cla_support=cla1 --float_support=fpu32 --tmu_support=tmu0 --vcu_support=vcu2 --fp_mode=relaxed --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/usblib/host" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/third_party/fatfs/src" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/utils" --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-c2000_6.4.6/include" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/usblib" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/third_party/fatfs/src" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/driverlib" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/usblib/device" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/inc" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/include" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_headers/include" --advice:performance=all -g --define=DISK0_USB_MSC --define=CPU1 --define=_FLASH --define=ccs_c2k --define=DISK1_USB_MSC --diag_warning=225 --display_error_number --diag_wrap=off --preproc_with_compile --preproc_dependency="controlSUITE/F2837xS/F2837xS_common/source/F2837xS_DBGIER.pp" --obj_directory="controlSUITE/F2837xS/F2837xS_common/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

controlSUITE/F2837xS/F2837xS_common/source/F2837xS_DefaultISR.obj: ../controlSUITE/F2837xS/F2837xS_common/source/F2837xS_DefaultISR.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-c2000_6.4.6/bin/cl2000" -v28 -ml -mt --cla_support=cla1 --float_support=fpu32 --tmu_support=tmu0 --vcu_support=vcu2 --fp_mode=relaxed --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/usblib/host" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/third_party/fatfs/src" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/utils" --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-c2000_6.4.6/include" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/usblib" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/third_party/fatfs/src" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/driverlib" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/usblib/device" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/inc" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/include" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_headers/include" --advice:performance=all -g --define=DISK0_USB_MSC --define=CPU1 --define=_FLASH --define=ccs_c2k --define=DISK1_USB_MSC --diag_warning=225 --display_error_number --diag_wrap=off --preproc_with_compile --preproc_dependency="controlSUITE/F2837xS/F2837xS_common/source/F2837xS_DefaultISR.pp" --obj_directory="controlSUITE/F2837xS/F2837xS_common/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

controlSUITE/F2837xS/F2837xS_common/source/F2837xS_Dma.obj: ../controlSUITE/F2837xS/F2837xS_common/source/F2837xS_Dma.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-c2000_6.4.6/bin/cl2000" -v28 -ml -mt --cla_support=cla1 --float_support=fpu32 --tmu_support=tmu0 --vcu_support=vcu2 --fp_mode=relaxed --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/usblib/host" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/third_party/fatfs/src" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/utils" --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-c2000_6.4.6/include" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/usblib" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/third_party/fatfs/src" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/driverlib" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/usblib/device" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/inc" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/include" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_headers/include" --advice:performance=all -g --define=DISK0_USB_MSC --define=CPU1 --define=_FLASH --define=ccs_c2k --define=DISK1_USB_MSC --diag_warning=225 --display_error_number --diag_wrap=off --preproc_with_compile --preproc_dependency="controlSUITE/F2837xS/F2837xS_common/source/F2837xS_Dma.pp" --obj_directory="controlSUITE/F2837xS/F2837xS_common/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

controlSUITE/F2837xS/F2837xS_common/source/F2837xS_ECap.obj: ../controlSUITE/F2837xS/F2837xS_common/source/F2837xS_ECap.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-c2000_6.4.6/bin/cl2000" -v28 -ml -mt --cla_support=cla1 --float_support=fpu32 --tmu_support=tmu0 --vcu_support=vcu2 --fp_mode=relaxed --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/usblib/host" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/third_party/fatfs/src" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/utils" --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-c2000_6.4.6/include" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/usblib" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/third_party/fatfs/src" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/driverlib" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/usblib/device" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/inc" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/include" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_headers/include" --advice:performance=all -g --define=DISK0_USB_MSC --define=CPU1 --define=_FLASH --define=ccs_c2k --define=DISK1_USB_MSC --diag_warning=225 --display_error_number --diag_wrap=off --preproc_with_compile --preproc_dependency="controlSUITE/F2837xS/F2837xS_common/source/F2837xS_ECap.pp" --obj_directory="controlSUITE/F2837xS/F2837xS_common/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

controlSUITE/F2837xS/F2837xS_common/source/F2837xS_EPwm.obj: ../controlSUITE/F2837xS/F2837xS_common/source/F2837xS_EPwm.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-c2000_6.4.6/bin/cl2000" -v28 -ml -mt --cla_support=cla1 --float_support=fpu32 --tmu_support=tmu0 --vcu_support=vcu2 --fp_mode=relaxed --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/usblib/host" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/third_party/fatfs/src" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/utils" --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-c2000_6.4.6/include" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/usblib" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/third_party/fatfs/src" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/driverlib" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/usblib/device" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/inc" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/include" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_headers/include" --advice:performance=all -g --define=DISK0_USB_MSC --define=CPU1 --define=_FLASH --define=ccs_c2k --define=DISK1_USB_MSC --diag_warning=225 --display_error_number --diag_wrap=off --preproc_with_compile --preproc_dependency="controlSUITE/F2837xS/F2837xS_common/source/F2837xS_EPwm.pp" --obj_directory="controlSUITE/F2837xS/F2837xS_common/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

controlSUITE/F2837xS/F2837xS_common/source/F2837xS_EQep.obj: ../controlSUITE/F2837xS/F2837xS_common/source/F2837xS_EQep.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-c2000_6.4.6/bin/cl2000" -v28 -ml -mt --cla_support=cla1 --float_support=fpu32 --tmu_support=tmu0 --vcu_support=vcu2 --fp_mode=relaxed --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/usblib/host" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/third_party/fatfs/src" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/utils" --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-c2000_6.4.6/include" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/usblib" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/third_party/fatfs/src" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/driverlib" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/usblib/device" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/inc" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/include" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_headers/include" --advice:performance=all -g --define=DISK0_USB_MSC --define=CPU1 --define=_FLASH --define=ccs_c2k --define=DISK1_USB_MSC --diag_warning=225 --display_error_number --diag_wrap=off --preproc_with_compile --preproc_dependency="controlSUITE/F2837xS/F2837xS_common/source/F2837xS_EQep.pp" --obj_directory="controlSUITE/F2837xS/F2837xS_common/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

controlSUITE/F2837xS/F2837xS_common/source/F2837xS_Emif.obj: ../controlSUITE/F2837xS/F2837xS_common/source/F2837xS_Emif.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-c2000_6.4.6/bin/cl2000" -v28 -ml -mt --cla_support=cla1 --float_support=fpu32 --tmu_support=tmu0 --vcu_support=vcu2 --fp_mode=relaxed --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/usblib/host" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/third_party/fatfs/src" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/utils" --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-c2000_6.4.6/include" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/usblib" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/third_party/fatfs/src" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/driverlib" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/usblib/device" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/inc" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/include" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_headers/include" --advice:performance=all -g --define=DISK0_USB_MSC --define=CPU1 --define=_FLASH --define=ccs_c2k --define=DISK1_USB_MSC --diag_warning=225 --display_error_number --diag_wrap=off --preproc_with_compile --preproc_dependency="controlSUITE/F2837xS/F2837xS_common/source/F2837xS_Emif.pp" --obj_directory="controlSUITE/F2837xS/F2837xS_common/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

controlSUITE/F2837xS/F2837xS_common/source/F2837xS_Gpio.obj: ../controlSUITE/F2837xS/F2837xS_common/source/F2837xS_Gpio.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-c2000_6.4.6/bin/cl2000" -v28 -ml -mt --cla_support=cla1 --float_support=fpu32 --tmu_support=tmu0 --vcu_support=vcu2 --fp_mode=relaxed --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/usblib/host" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/third_party/fatfs/src" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/utils" --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-c2000_6.4.6/include" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/usblib" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/third_party/fatfs/src" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/driverlib" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/usblib/device" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/inc" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/include" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_headers/include" --advice:performance=all -g --define=DISK0_USB_MSC --define=CPU1 --define=_FLASH --define=ccs_c2k --define=DISK1_USB_MSC --diag_warning=225 --display_error_number --diag_wrap=off --preproc_with_compile --preproc_dependency="controlSUITE/F2837xS/F2837xS_common/source/F2837xS_Gpio.pp" --obj_directory="controlSUITE/F2837xS/F2837xS_common/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

controlSUITE/F2837xS/F2837xS_common/source/F2837xS_I2C.obj: ../controlSUITE/F2837xS/F2837xS_common/source/F2837xS_I2C.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-c2000_6.4.6/bin/cl2000" -v28 -ml -mt --cla_support=cla1 --float_support=fpu32 --tmu_support=tmu0 --vcu_support=vcu2 --fp_mode=relaxed --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/usblib/host" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/third_party/fatfs/src" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/utils" --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-c2000_6.4.6/include" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/usblib" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/third_party/fatfs/src" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/driverlib" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/usblib/device" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/inc" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/include" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_headers/include" --advice:performance=all -g --define=DISK0_USB_MSC --define=CPU1 --define=_FLASH --define=ccs_c2k --define=DISK1_USB_MSC --diag_warning=225 --display_error_number --diag_wrap=off --preproc_with_compile --preproc_dependency="controlSUITE/F2837xS/F2837xS_common/source/F2837xS_I2C.pp" --obj_directory="controlSUITE/F2837xS/F2837xS_common/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

controlSUITE/F2837xS/F2837xS_common/source/F2837xS_Mcbsp.obj: ../controlSUITE/F2837xS/F2837xS_common/source/F2837xS_Mcbsp.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-c2000_6.4.6/bin/cl2000" -v28 -ml -mt --cla_support=cla1 --float_support=fpu32 --tmu_support=tmu0 --vcu_support=vcu2 --fp_mode=relaxed --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/usblib/host" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/third_party/fatfs/src" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/utils" --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-c2000_6.4.6/include" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/usblib" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/third_party/fatfs/src" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/driverlib" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/usblib/device" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/inc" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/include" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_headers/include" --advice:performance=all -g --define=DISK0_USB_MSC --define=CPU1 --define=_FLASH --define=ccs_c2k --define=DISK1_USB_MSC --diag_warning=225 --display_error_number --diag_wrap=off --preproc_with_compile --preproc_dependency="controlSUITE/F2837xS/F2837xS_common/source/F2837xS_Mcbsp.pp" --obj_directory="controlSUITE/F2837xS/F2837xS_common/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

controlSUITE/F2837xS/F2837xS_common/source/F2837xS_PieCtrl.obj: ../controlSUITE/F2837xS/F2837xS_common/source/F2837xS_PieCtrl.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-c2000_6.4.6/bin/cl2000" -v28 -ml -mt --cla_support=cla1 --float_support=fpu32 --tmu_support=tmu0 --vcu_support=vcu2 --fp_mode=relaxed --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/usblib/host" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/third_party/fatfs/src" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/utils" --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-c2000_6.4.6/include" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/usblib" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/third_party/fatfs/src" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/driverlib" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/usblib/device" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/inc" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/include" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_headers/include" --advice:performance=all -g --define=DISK0_USB_MSC --define=CPU1 --define=_FLASH --define=ccs_c2k --define=DISK1_USB_MSC --diag_warning=225 --display_error_number --diag_wrap=off --preproc_with_compile --preproc_dependency="controlSUITE/F2837xS/F2837xS_common/source/F2837xS_PieCtrl.pp" --obj_directory="controlSUITE/F2837xS/F2837xS_common/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

controlSUITE/F2837xS/F2837xS_common/source/F2837xS_PieVect.obj: ../controlSUITE/F2837xS/F2837xS_common/source/F2837xS_PieVect.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-c2000_6.4.6/bin/cl2000" -v28 -ml -mt --cla_support=cla1 --float_support=fpu32 --tmu_support=tmu0 --vcu_support=vcu2 --fp_mode=relaxed --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/usblib/host" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/third_party/fatfs/src" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/utils" --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-c2000_6.4.6/include" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/usblib" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/third_party/fatfs/src" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/driverlib" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/usblib/device" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/inc" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/include" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_headers/include" --advice:performance=all -g --define=DISK0_USB_MSC --define=CPU1 --define=_FLASH --define=ccs_c2k --define=DISK1_USB_MSC --diag_warning=225 --display_error_number --diag_wrap=off --preproc_with_compile --preproc_dependency="controlSUITE/F2837xS/F2837xS_common/source/F2837xS_PieVect.pp" --obj_directory="controlSUITE/F2837xS/F2837xS_common/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

controlSUITE/F2837xS/F2837xS_common/source/F2837xS_Sci.obj: ../controlSUITE/F2837xS/F2837xS_common/source/F2837xS_Sci.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-c2000_6.4.6/bin/cl2000" -v28 -ml -mt --cla_support=cla1 --float_support=fpu32 --tmu_support=tmu0 --vcu_support=vcu2 --fp_mode=relaxed --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/usblib/host" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/third_party/fatfs/src" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/utils" --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-c2000_6.4.6/include" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/usblib" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/third_party/fatfs/src" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/driverlib" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/usblib/device" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/inc" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/include" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_headers/include" --advice:performance=all -g --define=DISK0_USB_MSC --define=CPU1 --define=_FLASH --define=ccs_c2k --define=DISK1_USB_MSC --diag_warning=225 --display_error_number --diag_wrap=off --preproc_with_compile --preproc_dependency="controlSUITE/F2837xS/F2837xS_common/source/F2837xS_Sci.pp" --obj_directory="controlSUITE/F2837xS/F2837xS_common/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

controlSUITE/F2837xS/F2837xS_common/source/F2837xS_Spi.obj: ../controlSUITE/F2837xS/F2837xS_common/source/F2837xS_Spi.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-c2000_6.4.6/bin/cl2000" -v28 -ml -mt --cla_support=cla1 --float_support=fpu32 --tmu_support=tmu0 --vcu_support=vcu2 --fp_mode=relaxed --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/usblib/host" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/third_party/fatfs/src" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/utils" --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-c2000_6.4.6/include" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/usblib" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/third_party/fatfs/src" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/driverlib" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/usblib/device" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/inc" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/include" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_headers/include" --advice:performance=all -g --define=DISK0_USB_MSC --define=CPU1 --define=_FLASH --define=ccs_c2k --define=DISK1_USB_MSC --diag_warning=225 --display_error_number --diag_wrap=off --preproc_with_compile --preproc_dependency="controlSUITE/F2837xS/F2837xS_common/source/F2837xS_Spi.pp" --obj_directory="controlSUITE/F2837xS/F2837xS_common/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

controlSUITE/F2837xS/F2837xS_common/source/F2837xS_SysCtrl.obj: ../controlSUITE/F2837xS/F2837xS_common/source/F2837xS_SysCtrl.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-c2000_6.4.6/bin/cl2000" -v28 -ml -mt --cla_support=cla1 --float_support=fpu32 --tmu_support=tmu0 --vcu_support=vcu2 --fp_mode=relaxed --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/usblib/host" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/third_party/fatfs/src" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/utils" --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-c2000_6.4.6/include" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/usblib" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/third_party/fatfs/src" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/driverlib" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/usblib/device" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/inc" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/include" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_headers/include" --advice:performance=all -g --define=DISK0_USB_MSC --define=CPU1 --define=_FLASH --define=ccs_c2k --define=DISK1_USB_MSC --diag_warning=225 --display_error_number --diag_wrap=off --preproc_with_compile --preproc_dependency="controlSUITE/F2837xS/F2837xS_common/source/F2837xS_SysCtrl.pp" --obj_directory="controlSUITE/F2837xS/F2837xS_common/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

controlSUITE/F2837xS/F2837xS_common/source/F2837xS_TempSensorConv.obj: ../controlSUITE/F2837xS/F2837xS_common/source/F2837xS_TempSensorConv.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-c2000_6.4.6/bin/cl2000" -v28 -ml -mt --cla_support=cla1 --float_support=fpu32 --tmu_support=tmu0 --vcu_support=vcu2 --fp_mode=relaxed --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/usblib/host" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/third_party/fatfs/src" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/utils" --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-c2000_6.4.6/include" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/usblib" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/third_party/fatfs/src" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/driverlib" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/usblib/device" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/inc" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/include" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_headers/include" --advice:performance=all -g --define=DISK0_USB_MSC --define=CPU1 --define=_FLASH --define=ccs_c2k --define=DISK1_USB_MSC --diag_warning=225 --display_error_number --diag_wrap=off --preproc_with_compile --preproc_dependency="controlSUITE/F2837xS/F2837xS_common/source/F2837xS_TempSensorConv.pp" --obj_directory="controlSUITE/F2837xS/F2837xS_common/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

controlSUITE/F2837xS/F2837xS_common/source/F2837xS_Upp.obj: ../controlSUITE/F2837xS/F2837xS_common/source/F2837xS_Upp.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-c2000_6.4.6/bin/cl2000" -v28 -ml -mt --cla_support=cla1 --float_support=fpu32 --tmu_support=tmu0 --vcu_support=vcu2 --fp_mode=relaxed --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/usblib/host" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/third_party/fatfs/src" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/utils" --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-c2000_6.4.6/include" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/usblib" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/third_party/fatfs/src" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/driverlib" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/usblib/device" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/inc" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/include" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_headers/include" --advice:performance=all -g --define=DISK0_USB_MSC --define=CPU1 --define=_FLASH --define=ccs_c2k --define=DISK1_USB_MSC --diag_warning=225 --display_error_number --diag_wrap=off --preproc_with_compile --preproc_dependency="controlSUITE/F2837xS/F2837xS_common/source/F2837xS_Upp.pp" --obj_directory="controlSUITE/F2837xS/F2837xS_common/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

controlSUITE/F2837xS/F2837xS_common/source/F2837xS_sci_io.obj: ../controlSUITE/F2837xS/F2837xS_common/source/F2837xS_sci_io.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-c2000_6.4.6/bin/cl2000" -v28 -ml -mt --cla_support=cla1 --float_support=fpu32 --tmu_support=tmu0 --vcu_support=vcu2 --fp_mode=relaxed --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/usblib/host" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/third_party/fatfs/src" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/utils" --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-c2000_6.4.6/include" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/usblib" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/third_party/fatfs/src" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/driverlib" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/usblib/device" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/inc" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/include" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_headers/include" --advice:performance=all -g --define=DISK0_USB_MSC --define=CPU1 --define=_FLASH --define=ccs_c2k --define=DISK1_USB_MSC --diag_warning=225 --display_error_number --diag_wrap=off --preproc_with_compile --preproc_dependency="controlSUITE/F2837xS/F2837xS_common/source/F2837xS_sci_io.pp" --obj_directory="controlSUITE/F2837xS/F2837xS_common/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

controlSUITE/F2837xS/F2837xS_common/source/F2837xS_sdfm_drivers.obj: ../controlSUITE/F2837xS/F2837xS_common/source/F2837xS_sdfm_drivers.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-c2000_6.4.6/bin/cl2000" -v28 -ml -mt --cla_support=cla1 --float_support=fpu32 --tmu_support=tmu0 --vcu_support=vcu2 --fp_mode=relaxed --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/usblib/host" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/third_party/fatfs/src" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/utils" --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-c2000_6.4.6/include" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/usblib" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/third_party/fatfs/src" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/driverlib" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/usblib/device" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/inc" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/include" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_headers/include" --advice:performance=all -g --define=DISK0_USB_MSC --define=CPU1 --define=_FLASH --define=ccs_c2k --define=DISK1_USB_MSC --diag_warning=225 --display_error_number --diag_wrap=off --preproc_with_compile --preproc_dependency="controlSUITE/F2837xS/F2837xS_common/source/F2837xS_sdfm_drivers.pp" --obj_directory="controlSUITE/F2837xS/F2837xS_common/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

controlSUITE/F2837xS/F2837xS_common/source/F2837xS_struct.obj: ../controlSUITE/F2837xS/F2837xS_common/source/F2837xS_struct.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-c2000_6.4.6/bin/cl2000" -v28 -ml -mt --cla_support=cla1 --float_support=fpu32 --tmu_support=tmu0 --vcu_support=vcu2 --fp_mode=relaxed --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/usblib/host" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/third_party/fatfs/src" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/utils" --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-c2000_6.4.6/include" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/usblib" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/third_party/fatfs/src" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/driverlib" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/usblib/device" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/inc" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/include" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_headers/include" --advice:performance=all -g --define=DISK0_USB_MSC --define=CPU1 --define=_FLASH --define=ccs_c2k --define=DISK1_USB_MSC --diag_warning=225 --display_error_number --diag_wrap=off --preproc_with_compile --preproc_dependency="controlSUITE/F2837xS/F2837xS_common/source/F2837xS_struct.pp" --obj_directory="controlSUITE/F2837xS/F2837xS_common/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

controlSUITE/F2837xS/F2837xS_common/source/F2837xS_usDelay.obj: ../controlSUITE/F2837xS/F2837xS_common/source/F2837xS_usDelay.asm $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-c2000_6.4.6/bin/cl2000" -v28 -ml -mt --cla_support=cla1 --float_support=fpu32 --tmu_support=tmu0 --vcu_support=vcu2 --fp_mode=relaxed --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/usblib/host" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/third_party/fatfs/src" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/utils" --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-c2000_6.4.6/include" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/usblib" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/third_party/fatfs/src" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/driverlib" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/usblib/device" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/inc" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_common/include" --include_path="C:/Users/pskkd/Documents/GitHub/TMS_Skype_Petcam/controlSUITE/F2837xS/F2837xS_headers/include" --advice:performance=all -g --define=DISK0_USB_MSC --define=CPU1 --define=_FLASH --define=ccs_c2k --define=DISK1_USB_MSC --diag_warning=225 --display_error_number --diag_wrap=off --preproc_with_compile --preproc_dependency="controlSUITE/F2837xS/F2837xS_common/source/F2837xS_usDelay.pp" --obj_directory="controlSUITE/F2837xS/F2837xS_common/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '


